// Generated by CoffeeScript 1.10.0
(function() {
  var ConnectRedis, SocketIORedisStore, UUID;

  ConnectRedis = require('connect-redis');

  SocketIORedisStore = require('socket.io-redis');

  UUID = require('uuid');

  this.include = function() {
    var ExpressRedisStore, MemoryStore, redis_config, ref;
    if (this.cfg.redis != null) {
      redis_config = this.cfg.redis;
      ExpressRedisStore = ConnectRedis(this.session);
      this.use({
        session: {
          store: new ExpressRedisStore(redis_config),
          secret: (ref = cfg.redis.secret) != null ? ref : 'rock zappa rock',
          resave: true,
          saveUninitialized: true
        }
      });
      return this.io.adapter(SocketIORedisStore(redis_config));
    } else {
      MemoryStore = this.session.MemoryStore;
      return this.use({
        session: {
          store: new MemoryStore(),
          secret: UUID.v4(),
          resave: true,
          saveUninitialized: true
        }
      });
    }
  };

}).call(this);
